services:
  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=langchain
      - POSTGRES_PASSWORD=langchain
      - POSTGRES_DB=portfolio_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: