services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=langchain
      - POSTGRES_PASSWORD=langchain
      - POSTGRES_DB=portfolio_db